# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""
from datetime import datetime
startTime = datetime.now()


string1 = """SGSWLRDVWDWICTVLTDFKTWLQSKLLPRLPGVPFLSCQRGYKGVWRGDGIMQTTCPCGAQIAGHVKNGSMRIVGPKTC
SNTWHGTFPINAYTTGPCVPSPAPNYSKALWRVAAEEYVEVTRVGDFHYVTGMTTDNIKCPCQVPAPEFFTEVDGVRLHR
YAPACKPLLREEVTFQVGLNQYLVGSQLPCEPEPDVTVLTSMLSDPSHITAETAKRRLARGSPPSLASSSASQLSAPSLK
ATCTTHHDSPDADLIEANLLWRQEMGGNITRVESENKVVILDSFDPLRAEEGEREISVPAEILRKTRKFPPAMPIWARPD
YNPPLIESWKHPDYVPPVVHGCPLPATKAPPIPPPRRKRTVVLTESTVSSALAELATKTFGSSESSAVDSGTATAPLDQP
SDAGDTGSDVESYSSMPPLEGEPGDPDLSDGSWSTVSEEASEDVVCC"""

string2 = """SGSWLRDVWDWICTVLTDFKTWLQSKLLPRLPGVPFLSCQRGYKGVWRGDGIMQTTCPCGAQIAGHVKNGSMRIVGPKTC
SNTWHGTFPINAYTTGPCVPSPAPNYSKALWRVAAEEYVEVTRVGDFHYVTGMTTDNIKCPCQVPAPEFFTEVDGVRLHR
YAPACKPLLREEVTFQVGLNQYLVGSQLPCEPEPDVTVLTSMLSDPSHITAETAKRRLARGSPPSLASSSASQLSAPSLK
ATCTTHHDSPDADLIEANLLWRQEMGGNITRVESENKVVILDSFDPLRAEEGEREISVPAEILRKTRKFPPAMPIWARPD
YNPPLIESWKHPDYVPPVVHGCPLPATKAPPIPPPRRKRTVVLTESTVSSALAELATKTFGSSESSAVDSGTATAPLDQP
PDAGDTGSDVESYSSMPPLEGEPGDPDLSDGSWSTVSEEASEDVVCC"""

string4 = "1234512"
string3 = "abcdeab"
seqList = [string1, string2]


sizeOfSubstr = (1,2,3,4)

setSubStr = set()
listSubString = []

for sizeOfSub in sizeOfSubstr: #số lượng kí tự của substr
    startIndexOfCurSize = len(listSubString)
    for seq in seqList: #duyệt từng sequence
        sizeOfSeq = len(seq)
        for index in xrange(0,sizeOfSeq-sizeOfSub+1): # duyệt substr
            curSubStr = seq[index: index+sizeOfSub]
            try:
                #chỉ tìm trong các sub string có cùng số lượng kí tự nên có startIndexOfCurSize
                foundIndex = listSubString.index(curSubStr, startIndexOfCurSize)
            except ValueError:
                listSubString.append(curSubStr)

            
print datetime.now() - startTime
